class Messeges:
    no_water = "No water, fill the water tank"
    no_coffee = "No coffee beans, fill the coffee tank"
    checking_coffee = "Checking coffee..."
    preparing_espresso = "Preparing Espresso, please wait a moment"
    coffee_is_ready = "Coffee is ready, take your drink"
    left_coffee_in_tank = "Coffee in tank: {0} grams"
    preparing_americano = "Preparing Americano, please wait a moment"
    canceled_order = "Order was canceled"
    no_coffee_selected = "No coffee selected. Please select coffee."
